image:
  - Visual Studio 2017
  - Ubuntu
configuration:
  - Release
  - Debug
environment:
  docs_deploy_secret:
    secure: 6Xz1lO3ZQLcnQhU9lpG+LbLkz2mtMLlS9Ro8LyBM8Xk=
install:
  - ps: appveyor/Install.ps1
before_build:
  - ps: appveyor/BeforeBuild.ps1
build_script:
  - ps: appveyor/BuildScript.ps1
test_script:
  - ps: appveyor/TestScript.ps1
deploy_scripts:
  - ps: appveyor/DeployScripts.ps1
