image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
before_build:
  - cmd: |
      cd dependencies
      cmake . -G "Visual Studio 15 2017 Win64"
      cd ..
      mkdir build
      cd build
      cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_EXAMPLE=ON -DBUILD_TESTS=ON
build:
  project: build\logger.sln
  verbosity: minimal
  parallel: true
test_script:
  - cmd: .\%CONFIGURATION%\tests.exe
